spring.application.name=nextstep

spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:44864/railway
spring.datasource.username=postgres
spring.datasource.password=YOCBcVTevodFaZUSybegQwmioQNsczYp

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HikariCP - evita timeout com o proxy do Railway
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nextstep.sistema@gmail.com
spring.mail.password=mtfv gqgp ikyu rtsa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Na entrega final do projeto, alterar para o e-mail da diretora real.
nextstep.email.diretora=seu-email-pessoal@gmail.com
