spring.application.name=nextstep

spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:44864/railway
spring.datasource.username=postgres
spring.datasource.password=YOCBcVTevodFaZUSybegQwmioQNsczYp

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HikariCP - evita timeout com o proxy do Railway
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000